import {
  AdventureTshirt,
  BlackLetherWatch,
  ClassicWatch,
  ColourfulShirt,
  CrewNeckTshirt,
  DigitalWatch,
  DragonTshirt,
  ElegantMinding,
  ElegantWatch,
  Ellipse1,
  Ellipse2,
  Ellipse3,
  Frame28,
  Frame29,
  Frame30,
  Frame31,
  GoldenWatch,
  HandmanWristWatch,
  HandsomeStylish,
  IanDooleyTshirt,
  ManInBlack,
  ManInWhite,
  ManOnWite,
  ManOrangeTshirt,
  ManPosing,
  ManWearingStripedPoloShirt,
  Minimalist,
  SilverWatch,
  SmartWatch,
  TimeChangeWatch,
  Tshirt,
  WomanWearingStripedBlouse,
  YoungMaleRedShirt,
  YoungManWithAfro,
} from "../assets";

export const imageSlider = [
  {
    id: 1,
    img: Frame28,
    alt: "Beautiful smiling woman",
  },
  {
    id: 2,
    img: Frame30,
    alt: "Hell Shoe",
  },
  {
    id: 3,
    img: Frame29,
    alt: "Two Georgeous Women",
  },
  {
    id: 4,
    img: Frame31,
    alt: "Two HandSome Men",
  },
];

export const products = [
  {
    id: 1,
    img: ColourfulShirt,
    caterogy: "Men",
    price: "$19.99",
    description: "Vintage logo graphics tee",
    alt: "Studio shot of unconfident embarrassed young man with stubble in colourful shirt feels confused ",
    rate: "4.7",
    reviewa: "(120Reviews)",
  },
  {
    id: 2,
    img: ManInBlack,
    caterogy: "Women",
    price: "$30.99",
    description: "Classic Black long-sleeve",
    alt: "Man in black sweater and black bucket hat youth apparel shoot",
    rate: "5.0",
    reviewa: "(200Reviews)",
  },
  {
    id: 3,
    img: ManInWhite,
    caterogy: "men",
    price: "$30.99",
    description: "Comfortable white round neck",
    alt: "Young man in white t-shirt and black pants holding hands on waist and looking serious",
    rate: "5.0",
    reviewa: "(200Reviews)",
  },
  {
    id: 4,
    img: ManPosing,
    caterogy: "Men",
    price: "$19.99",
    description: "Vintage logo graphics tee",
    alt: "Young handsome man posing in quarry",
    rate: "4.7",
    reviewa: "(200Reviews)",
  },
  {
    id: 5,
    img: Tshirt,
    caterogy: "Unisex",
    price: "$30.99",
    description: "Classic Black long-sleeve",
    alt: "T-shirt painting indoors still life",
    rate: "5.0",
    reviewa: "(200Reviews)",
  },
  {
    id: 6,
    img: HandsomeStylish,
    caterogy: "men",
    price: "$30.99",
    description: "Comfortable white round neck",
    alt: "Portrait of handsome confident stylish hipster lambersexual modelman dressed in over size tshirt and jeans fashion male",
    rate: "5.0",
    reviewa: "(200Reviews)",
  },
];

export const shirts = [
  {
    id: 1,
    img: DragonTshirt,
    price: `${"$9.5"}`,
    name: "Baseball shirt",
    discription: "Duotone Thunder Dragons Baseball Design",
    alt: "duotone-thunder-dragons-baseball-t-shirt-design",
  },
  {
    id: 2,
    img: ElegantMinding,
    price: `${"$8.9"}`,
    name: "Elegant MInd",
    discription: "Elegant Minding Small Business Owner T-shirt",
    alt: "elegant-minding-small-business-owner-t-shirt",
  },
  {
    id: 3,
    img: ManOrangeTshirt,
    price: `${"$12"}`,
    name: "Orange shirt",
    discription: "Front View Man Posing Studio",
    alt: "front-view-man-posing-studio",
  },
  {
    id: 4,
    img: Minimalist,
    price: `${"$5"}`,
    name: "Big Dream Shirt",
    discription: "Minimalist Small Business Big Dreams T-shirt",
    alt: "minimalist-small-business-big-dreams-t-shirt",
  },
  {
    id: 5,
    img: YoungMaleRedShirt,
    price: `${"$11.5"}`,
    name: "Red shirt",
    discription: "front view young Male Red-shirt",
    alt: "front-view-young-male-red-shirt-black-wall",
  },
  {
    id: 6,
    img: YoungManWithAfro,
    price: `${"$10.5"}`,
    name: "Clean White Shirt",
    discription: "portrait young man with afro dreadlocks hairstyle",
    alt: "portrait-young-man-with-afro-dreadlocks-hairstyle",
  },
];

export const testimonial = [
  {
    id: 1,
    img: Ellipse1,
    name: "Akinlotan Matthew",
    review:
      "UrbanStyle is my fashion sanctuary! The quality, style, and uniqueness of their products always impress me. I've been a loyal customer for years, and I keep coming back for more. It's the place where I find those statement pieces that set trends, and their customer service is top-notch",
  },
  {
    id: 2,
    img: Ellipse2,
    name: "Hannah Ademola",
    review:
      "UrbanStyle is the go-to place for all my urban fashion needs. I love exploring their extensive selection of streetwear. The variety of styles and brands they offer is incredible. The website is easy to navigate, and I can always count on fast delivery. UrbanStyle has become my urban fashion haven",
  },
  {
    id: 3,
    img: Ellipse3,
    name: "Helen Adewunmi",
    review:
      "UrbanStyle is the go-to place for all my urban fashion needs. I love exploring their extensive selection of streetwear. The variety of styles and brands they offer is incredible. The website is easy to navigate, and I can always count on fast delivery. UrbanStyle has become my urban fashion haven",
  },
];

export const moreShirts = [
  {
    id: 1,
    img: ManOnWite,
    price: `${"$9.5"}`,
    name: "White Round Neck",
    discription: "White Round Neck",
    alt: "Man on White Round Neck",
  },
  {
    id: 2,
    img: ManWearingStripedPoloShirt,
    price: `${"$8.9"}`,
    name: "Striped Polo Shirt",
    discription: "man wearing striped polo shirt",
    alt: "man_wearing_striped_polo_shirt",
  },
  {
    id: 3,
    img: CrewNeckTshirt,
    price: `${"$12"}`,
    name: "Orange shirt",
    discription: "Front View Man Posing Studio",
    alt: "front-view-man-posing-studio",
  },
  {
    id: 4,
    img: IanDooleyTshirt,
    price: `${"$5"}`,
    name: "Ian Dooley T-shirt",
    discription: "Tall White Man Wearing Ian Dooley T-shirt",
    alt: "ian-dooley t-shirt",
  },
  {
    id: 5,
    img: WomanWearingStripedBlouse,
    price: `${"$11.5"}`,
    name: "Striped Blouse",
    discription: "Funky Afro American Young Woman Wearing Striped Blouse",
    alt: "funky_afro_american_young_woman_wearing_striped_blouse",
  },
  {
    id: 6,
    img: AdventureTshirt,
    price: `${"$10.5"}`,
    name: "Adventure T-shirt",
    discription: "Simple Monocolor find your Adventure T-shirt",
    alt: "simple-monocolor-find-your-adventure-t-shirt",
  },
];

export const writstWatch = [
  {
    id: 1,
    image: GoldenWatch,
    alt: "closeup-shot-golden-watch-isolated",
    name: "GoldenWatch",
    price: `${"$100.89"}`,
    discription: "Closeup Shot Golden Watch",
  },
  {
    id: 2,
    image: HandmanWristWatch,
    alt: "hand-man-wrist-watch",
    name: "Handman Wrist Watch",
    price: `${"$50"}`,
    discription: "Hand Man Wrist Watch",
  },
  {
    id: 3,
    image: SmartWatch,
    alt: "smart-watch-realistic-image-black",
    name: "Smart Wrist Watch",
    price: `${"$80"}`,
    discription: "Smart Watch Realistic Image Black",
  },
  {
    id: 4,
    image: ElegantWatch,
    alt: "elegant-watch-with-silver-golden-chain",
    name: "Elegant Wrist Watch",
    price: `${"$150.90"}`,
    discription: "Elegant Wrist Watch With Silver Golden Chain",
  },
  {
    id: 5,
    image: SilverWatch,
    alt: "elegant-watch-with-silver-golden-chain",
    name: "Silver Golden Watch",
    price: `${"$250.90"}`,
    discription: "Elegant Wrist Watch With Silver Golden Chain",
  },
  {
    id: 6,
    image: TimeChangeWatch,
    alt: "close-up-clock-with-time-change",
    name: "Time Change Wrist Watch",
    price: `${"$200"}`,
    discription: "close up clock with time change",
  },
];

export const moreWatches = [
  {
    id: 1,
    image: DigitalWatch,
    alt: "DigitalWatch",
    name: "Apple Watch",
    price: `${"$200"}`,
    discription: "apple digital watch",
  },
  {
    id: 2,
    image: ClassicWatch,
    alt: "Classic Watch",
    name: "Classic Watch",
    price: `${"$150"}`,
    discription: "black classic watch",
  },
  {
    id: 3,
    image: BlackLetherWatch,
    alt: "Black Lether Watch",
    name: "Lether Watch",
    price: `${"$300"}`,
    discription: "black lether watch",
  },
];
